[{
    id: 17592194523853,
    name: "Consumo - Energia - Área Comum",
    description: "Consumo - Energia - Área Comum é uma cobrança referente ao consumo de energia nas áreas comuns do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619791-Consumos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Consumo - Energia - Área Comum",
    url: "consumo-energia-area-comum"
}, {
    id: 17592194523856,
    name: "Rateio - Contas de consumo",
    description: "Rateio - Contas de consumo é uma cobrança referente ao consumo de água",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619791-Consumos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Rateio - Contas de consumo",
    url: "rateio-contas-consumo"
}, {
    id: 17592194523855,
    name: "Taxa de leitura para contas de consumo",
    description: "Taxa de leitura para contas de consumo é um valor cobrado por empresa terceirizada para realizar a leitura dos consumos de energia",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619791-Consumos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Taxa de leitura para contas de consumo",
    url: "taxa-leitura"
}, {
    id: 17592194523858,
    name: "Cota Condominial Complementar",
    description: "Cota Condominial Complementar é uma arrecadação destinada ao pagamento das despesas básicas e fixas do condomínio",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629032-Cotas-condominiais",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Cota Condominial Complementar",
    url: "cota-condominial-complementar"
}, {
    id: 17592240235307,
    name: "Proteção 5A - Reparos",
    description: "Despesas associadas a reparos pendentes no imóvel após a rescisão do contrato (ou saída do imóvel).",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620251",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Proteção 5A - Reparos",
    url: "protecao-5A-reparos"
}, {
    id: 17592194523857,
    name: "Cota Condominial",
    description: "Cota Condominial é uma arrecadação destinada ao pagamento das despesas básicas e fixas do condomínio",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629032-Cotas-condominiais",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Cota Condominial",
    url: "cota-condominial"
}, {
    id: 17592194523860,
    name: "Cota Condominial - Subsolo",
    description: "Cota Condominial - Subsolo é uma arrecadação destinada ao pagamento das despesas básicas e fixas do subsolo do condomínio",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629032-Cotas-condominiais",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Cota Condominial - Subsolo",
    url: "cota-condominial-subsolo"
}, {
    id: 17592194523859,
    name: "Cota Condominial - Garagem",
    description: "Cota Condominial - Garagem é uma arrecadação destinada ao pagamento das despesas básicas e fixas da garagem do condomínio",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629032-Cotas-condominiais",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Cota Condominial - Garagem",
    url: "cota-condominial-garagem"
}, {
    id: 17592194523863,
    name: "Encargos Trabalhistas - 13º salário/Férias de funcionários",
    description: "Encargos Trabalhistas - 13º salário/Férias de funcionários é uma despesa referente ao pagamento dos 13º salários e/ou das férias dos funcionários do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619851-Encargos-e-honor%C3%A1rios",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Encargos Trabalhistas - 13º salário/Férias de funcionários",
    url: "encargos-trabalhistas"
}, {
    id: 17592194523866,
    name: "Honorários - Síndico",
    description: "Honorários - Sindíco é uma despesa referente ao pagamento dos salários",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619851-Encargos-e-honor%C3%A1rios",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Honorários - Síndico",
    url: "honorarios-sindico"
}, {
    id: 17592194523865,
    name: "Honorários - Advocatícios",
    description: "Honorários - Advocatícios é uma despesa referente ao pagamento de advogados para o condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619851-Encargos-e-honor%C3%A1rios",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Honorários - Advocatícios",
    url: "honorarios-advocaticios"
}, {
    id: 17592194523867,
    name: "Honorários - Prestador de serviço",
    description: "Honorários - Prestador de serviço é uma despesa referente ao pagamento de prestadores de serviço para o condomínio..",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619851-Encargos-e-honor%C3%A1rios",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Honorários - Prestador de serviço",
    url: "honorarios-prestador"
}, {
    id: 17592194523872,
    name: "Fundo - Manutenção",
    description: "Fundo - Manutenção é um valor arrecadado para o fundo destinado à manutenção e conservação das instalações e equipamentos hidráulicos",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629132-Fundos-para-manuten%C3%A7%C3%A3o",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Fundo - Manutenção",
    url: "fundo-manutencao"
}, {
    id: 17592194523874,
    name: "Manutenção",
    description: "Manutenção - é um valor destinado à manutenção e conservação das instalações e equipamentos hidráulicos",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629132-Fundos-para-manuten%C3%A7%C3%A3o",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Manutenção",
    url: "manutenção"
}, {
    id: 17592194523873,
    name: "Fundo - Estacionamento (Manutenção)",
    description: "Fundo - Estacionamento (Manutenção) é um valor arrecadado para o fundo destinado à manutenção e conservação das instalações do estacionamento/ garagem.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629132-Fundos-para-manuten%C3%A7%C3%A3o",
    "disabled-at": "2018-08-14T20:22:46+0000",
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Fundo - Estacionamento (Manutenção)",
    url: "fundo-estacionamento-manutencao"
}, {
    id: 17592234475336,
    name: "Manutenção - Complementar",
    description: "Manutenção - Complementar é um valor destinado à manutenção e conservação das instalações e equipamentos hidráulicos.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629132-Fundos-para-manuten%C3%A7%C3%A3o",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Manutenção - Complementar",
    url: "manutencao-complementar"
}, {
    id: 17592194523882,
    name: "Imposto - Energia / Água",
    description: "Imposto - Energia / Água - Quando algum imposto ainda não foi desmembrado pela prefeitura",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620051-Impostos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Imposto - Energia / Água",
    url: "imposto-energia-agua"
},
{
    id: 17592194523908,
    name: "Uso - Assistência médica",
    description: "Uso - Assistência médica é uma cobrança gerada pelo uso da assistência médica do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Assistência médica",
    url: "uso-assistencia"
}, {
    id: 17592209028830,
    name: "Deficit Orçamentário - Resp. Inquilino",
    description: "Deficit Orçamentário é um valor cobrado do inquilino quando o condomínio está sem dinheiro e precisou criar uma cobrança para sanar os gastos ordinários e equilibrar as contas.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620251-Outras-despesas",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Deficit Orçamentário - Resp. Inquilino",
    url: "deficit-orcamentario-inquilino"
}, {
    id: 17592194523910,
    name: "Uso - Camareira",
    description: "Uso - Camareira é a cobrança gerada pelo uso dos serviços de camareira do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Camareira",
    url: "uso-camareira"
}, {
    id: 17592194523909,
    name: "Uso - Associação",
    description: "Uso - Associação é uma cobrança gerada pelo uso dos serviços de associação do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Associação",
    url: "uso-associacao"
}, {
    id: 17592194523912,
    name: "Uso - Estacionamento",
    description: "Uso - Estacionamento é a cobrança gerada pelo uso do estacionamento do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Estacionamento",
    url: "uso-estacionamento"
}, {
    id: 17592194523911,
    name: "Uso - Churrasqueira",
    description: "Uso - Churrasqueira é a cobrança gerada pelo uso da churrasqueira do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Churrasqueira",
    url: "uso-churrasqueira"
}, {
    id: 17592194523914,
    name: "Uso - Internet",
    description: "Uso - Internet é a cobrança gerada pelo uso do plano de internet do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Internet",
    url: "uso-internet"
}, {
    id: 17592194523913,
    name: "Uso - Garagem",
    description: "Uso - Garagem é a cobrança gerada pelo uso da garagem do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Garagem",
    url: "uso-garagem"
}, {
    id: 17592194523916,
    name: "Uso - Manobrista",
    description: "Uso - Manobrista é a cobrança gerada pelo uso do serviço de manobrista do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Manobrista",
    url: "uso-manobrista"
}, {
    id: 17592194523915,
    name: "Uso - Lavanderia",
    description: "Uso - Lavanderia é a cobrança gerada pelo uso da lavanderia do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Lavanderia",
    url: "uso-lavanderia"
}, {
    id: 17592194523918,
    name: "Uso - Salão de festas",
    description: "Uso - Salão de festas é a cobrança gerada pelo uso do salão de festas do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Salão de festas",
    url: "uso-salao"
}, {
    id: 17592194523917,
    name: "Uso - Programa Esportivo/Lazer",
    description: "Uso - Programa Esportivo/Lazer é a cobrança gerada pelo uso dos programas de personal fitness ou de atividades fisicas.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Programa Esportivo/Lazer",
    url: "uso-programa-esportivo"
}, {
    id: 17592194523920,
    name: "Uso - Serviço Condomínio",
    description: "Uso - Serviço Condomínio é a cobrança gerada pelo uso individual dos serviços do condomínio (como salão de festas e lavanderia) e pela aquisição de itens de acesso (controle, cartão). Também pode ser referente à multa por infração das regras do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Serviço Condomínio",
    url: "uso-servico-condominio"
}, {
    id: 17592194523919,
    name: "Proteção Residencial - Condomínio",
    description: "Uso - Seguro Condomínio é a cobrança do seguro contratado pelo condomínio",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629292-Rateios-para-reparos-e-melhorias",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Proteção Residencial - Condomínio",
    url: "protecao-residencial-condominio"
}, {
    id: 17592194523922,
    name: "Uso - TV",
    description: "Uso - TV é a cobrança gerada pelo uso da TV por assinatura do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - TV",
    url: "uso-tv"
}, {
    id: 17592194523921,
    name: "Uso - Telefone",
    description: "Uso - Telefone é a cobrança gerada pelo uso do plano de telefone do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Uso - Telefone",
    url: "uso-telefone"
}, {
    id: 17592194523923,
    name: "Multa - Infração regulamentar",
    description: "Multa - Infração regulamentar é a cobrança gerada devido à infração do regulamento do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629432-Uso-dos-servi%C3%A7os-do-condom%C3%ADnio",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Multa - Infração regulamentar",
    url: "multa-infracao-regulamentar"
}, {
    id: 17592194523925,
    name: "Despesas - Correio",
    description: "Despesas - Correio é um valor arrecadado para pagar as despesas de correio com envio de comunicados e atas de condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000628451-Outras-despesas",
    "disabled-at": "2018-08-14T20:12:54+0000",
    "from": "quinto-andar",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Despesas - Correio",
    url: "despesas-correio"
}, {
    id: 17592194523929,
    name: "Tarifa - Boleto",
    description: "Tarifa - Boleto é uma tarifa cobrada pelo banco para emissão do boleto de condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620251-Outras-despesas",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Tarifa - Boleto",
    url: "tarifa-boleto"
}, {
    id: 17592234475325,
    name: "Fundo Manutenção - Complementar",
    description: "Fundo Manutenção - Complementar é um valor arrecadado para o fundo destinado à manutenção e conservação das instalações e equipamentos hidráulicos.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629132-Fundos-para-manuten%C3%A7%C3%A3o",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Fundo Manutenção - Complementar",
    url: "fundo-manutencao-complementar"
}, {
    id: 17592209028971,
    name: "Fundo - Estacionamento - Manutenção",
    description: "Fundo - Estacionamento - Manutenção é um valor arrecadado para o fundo destinado à manutenção e conservação das instalações do estacionamento/ garagem.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000629132-Fundos-para-manuten%C3%A7%C3%A3o",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Fundo - Estacionamento - Manutenção",
    url: "fundo-estacionamento-manutencao"
}, {
    id: 17592234475233,
    name: "Encargos Trabalhistas - Complementar",
    description: "Encargos Trabalhistas - Complementar é uma despesa referente ao pagamento dos salários dos funcionários do condomínio.  ",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619851-Encargos-e-honor%C3%A1rios",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Encargos Trabalhistas - Complementar",
    url: "encargos-trabalhistas-complementar"
}, {
    id: 17592196659238,
    name: "Bonificação de fim de ano (Funcionários condomínio)",
    description: "Despesa eventual normalmente acordada em assembleia e cobrada pela administradora do seu condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620251-Outras-despesas",
    "disabled-at": "2018-08-14T20:30:15+0000",
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Bonificação de fim de ano (Funcionários condomínio)",
    url: "bonificacao-fim-ano"
}, {
    id: 17592203430354,
    name: "Transporte Coletivo",
    description: "Transporte Coletivo é destinado ao pagamento dos custos operacionais do transporte coletivo oferecido pelo condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620251-Outras-despesas",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Transporte Coletivo",
    url: "transporte-coletivo"
}, {
    id: 17592203430356,
    name: "Consumo - Gás - Piscina",
    description: "Consumo - Gás - Piscina é uma cobrança referente ao consumo de fás nas áreas comuns do condomínio. ",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619791-Consumos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Consumo - Gás - Piscina",
    url: "consumo-gas-piscina"
}, {
    id: 17592203430355,
    name: "Consumo - Água - Quente",
    description: "Consumo - Água - Quente é uma cobrança referente ao consumo de água quente nas áreas comuns do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619791-Consumos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Consumo - Água - Quente",
    url: "consumo-agua-quente"
}, {
    id: 17592203430357,
    name: "Consumo - Gás - Fogão",
    description: "Consumo - Gás - Fogão é uma cobrança referente ao consumo de gás nas áreas comuns do condomínio.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000619791-Consumos",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Consumo - Gás - Fogão",
    url: "consumo-gas-fogao",
}, {
    id: 17592203430359,
    name: "Ajuste - Condomínio",
    description: "Ajuste - Condomínio é um ajuste de valor realizado ao final da locação para zerar o balanço entre as despesas pagas e cobradas pelo QuintoAndar durante a locação. O ajuste é feito em 2 etapas: a primeira é entre o primeiro e penúltimo boletos pagos de condomínio, e a segunda é a diferença proporcional, dos dias vividos do último mês, das despesas ordinárias que cobramos e pagamos na fatura de rescisão. Por fim, as duas etapas são somadas e chega-se ao valor final de ajuste para as partes. Isto ocorre, pois utilizamos o valor referencial do último boleto na cobrança mensal de faturas.",
    "help-link": "https://help.quintoandar.com.br/hc/pt-br/articles/115000620251-Outras-despesas",
    "disabled-at": null,
    "from": "tenant",
    "to": "quinto-andar",
    expenseGroup: "Ordinarias",
    searchable: "Ajuste - Condomínio",
    url: "ajuste-condominio"
}]